### ISSUE TITLE
Login no validado

### ISSUE THREAD

**Issue by Nidev-lab** [nicosalasaraoz/proyecto_final_blog_news#1]
## Proceso

1. Ingrese a la pagina.
2. Intente loguearme con un usuario no registrado.

## Resultado esperado

•Un aviso de que los datos ingresados no son correctos.

## Resultado actual

•Puedo loguearme con un usuario sin problema alguno.

## Captura

![image](https://github.com/nicosalasaraoz/proyecto_final_blog_news/assets/53904695/3056e33a-216d-4fde-b437-fee40d784dd6)

![image](https://github.com/nicosalasaraoz/proyecto_final_blog_news/assets/53904695/38b8a017-08db-45a6-980b-f492448c79ac)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by nicosalasaraoz** [comment]
como estas nico, ahi desde el front le impido el ingreso si no tiene status 200 que viene del back.
