### ISSUE TITLE
Formulario de registro

### ISSUE THREAD

**Issue by Nidev-lab** [nicosalasaraoz/proyecto_final_blog_news#3]
## Proceso

1. Ingrese a la pagina.
2. Quise registrarme con un nuevo usuario.

## Resultado esperado

• Que al colocar los datos solicitados en el formulario no se permitan numeros ni signos donde va el nombre.

## Resultado actual

• Puedo colocar numeros y signos donde va el nombre .

## Captura

![image](https://github.com/nicosalasaraoz/proyecto_final_blog_news/assets/53904695/3a3bba3f-b405-447d-9fb2-f4e7144c920a)
![image](https://github.com/nicosalasaraoz/proyecto_final_blog_news/assets/53904695/88f23ed1-1c37-4893-9ecc-022324eaa3c1)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by nicosalasaraoz** [comment]
agregue el pattern con validaciones para que el usuario ingrese nombre valido
