### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by Nidev-lab** [nicosalasaraoz/proyecto_final_blog_news#5]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario normal.

## Resultado esperado

• Una vez logueado no poder acceder a la sección de admin si el usuario no es admin.

## Resultado actual

• Al loguearme con cualquier usuario entro directamente a la sección de admin.

## Captura

![image](https://github.com/nicosalasaraoz/proyecto_final_blog_news/assets/53904695/5b356c08-9a0f-478b-9738-7e9b6f2ebfdd)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Hola Nico como estas? Te recomiendo que crees un usuario admin único que sea el encargado de designar a los demás usuarios desde un panel de admin, y que los usuarios que se registren solo sean usuarios normales a menos que el admin los designe como admin.

**Comment by nicosalasaraoz** [comment]
hola nico, como estas? dale si, lo imaginaba. lo que pasa es que no deberia haber usuario normal porque es un blog. igualmente lo voy a hacer. gracias

**Comment by nicosalasaraoz** [comment]
Hola como estas Nico? a los usuarios comunes los dirijo a la pagina principal, no hace nada pero no pueden editar, los admin si y el administrador es name"administrador", email "rolling@code.com", pass "Admin1234#" rol "admin". Cualquier cosa avisame. Abrazo y gracias
